import { Theme, spacing, radii, typography } from './tokens';

export const darkTheme: Theme = {
  dark: true,
  colors: {
    background: '#141517',
    surface: '#1E1F23',
    surfaceVariant: '#2C2E33',
    primary: '#748FFC',
    primaryContainer: '#364FC7',
    onPrimary: '#FFFFFF',
    secondary: '#9775FA',
    secondaryContainer: '#5F3DC4',
    error: '#FF6B6B',
    errorContainer: '#862E2E',
    onError: '#FFFFFF',
    success: '#51CF66',
    successContainer: '#1B5E20',
    warning: '#FFD43B',
    warningContainer: '#7A5200',
    textPrimary: '#E9ECEF',
    textSecondary: '#868E96',
    textDisabled: '#495057',
    textInverse: '#141517',
    border: '#373A40',
    borderFocused: '#748FFC',
    overlay: 'rgba(0, 0, 0, 0.7)',
    skeleton: '#2C2E33',
  },
  spacing,
  radii,
  typography,
  shadows: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 2,
    },
    modal: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.5,
      shadowRadius: 12,
      elevation: 8,
    },
  },
};
