import { Theme, spacing, radii, typography } from './tokens';

export const darkTheme: Theme = {
  dark: true,
  colors: {
    background: '#0F1117',
    surface: '#1A1D27',
    surfaceVariant: '#252832',
    glassBg: 'rgba(26, 29, 39, 0.85)',
    primary: '#7B93FF',
    primaryContainer: '#2D3A8C',
    onPrimary: '#FFFFFF',
    secondary: '#A78BFA',
    secondaryContainer: '#4C2D8C',
    error: '#FF6B6B',
    errorContainer: '#7A2020',
    onError: '#FFFFFF',
    success: '#51CF66',
    successContainer: '#1B4A20',
    warning: '#FFD43B',
    warningContainer: '#6D4C00',
    textPrimary: '#ECEEF2',
    textSecondary: '#8B92A0',
    textDisabled: '#434857',
    textInverse: '#0F1117',
    border: '#2E3240',
    borderFocused: '#7B93FF',
    overlay: 'rgba(0, 0, 0, 0.65)',
    skeleton: '#252832',
    accentGradientStart: '#7B93FF',
    accentGradientEnd: '#A78BFA',
  },
  spacing,
  radii,
  typography,
  shadows: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 3,
    },
    cardHover: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 16,
      elevation: 6,
    },
    modal: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.5,
      shadowRadius: 24,
      elevation: 12,
    },
  },
};
