import { Theme, spacing, radii, typography, iconSize } from './tokens';

export const lightTheme: Theme = {
  dark: false,
  colors: {
    background: '#F5F0FF',
    surface: '#FFFFFF',
    surfaceVariant: '#EDE5FF',
    surfaceElevated: '#FFFFFF',
    primary: '#7C3AED',
    primaryContainer: '#EDE5FF',
    onPrimary: '#FFFFFF',
    secondary: '#0EA5E9',
    secondaryContainer: '#E0F2FE',
    accent: '#14B8A6',
    error: '#EF4444',
    errorContainer: '#FEE2E2',
    onError: '#FFFFFF',
    success: '#10B981',
    successContainer: '#D1FAE5',
    warning: '#F59E0B',
    warningContainer: '#FEF3C7',
    textPrimary: '#0F172A',
    textSecondary: '#64748B',
    textDisabled: '#94A3B8',
    textInverse: '#FFFFFF',
    border: '#DDD0F5',
    borderFocused: '#7C3AED',
    overlay: 'rgba(15, 23, 42, 0.5)',
    skeleton: '#DDD0F5',
    headerBackground: '#7C3AED',
    headerText: '#FFFFFF',
    tabBar: '#FFFFFF',
    tabBarBorder: '#EDE5FF',
    gridIconBg: '#F0E8FF',
    gradientStart: '#7C3AED',
    gradientEnd: '#A855F7',
    cardGlow: 'rgba(124, 58, 237, 0.08)',
  },
  spacing,
  radii,
  typography,
  iconSize,
  shadows: {
    card: {
      shadowColor: 'rgba(124, 58, 237, 0.12)',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 12,
      elevation: 3,
    },
    modal: {
      shadowColor: 'rgba(99, 102, 241, 0.14)',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 1,
      shadowRadius: 24,
      elevation: 8,
    },
  },
};
