import { Theme, spacing, radii, typography } from './tokens';

export const lightTheme: Theme = {
  dark: false,
  colors: {
    background: '#FAFBFC',
    surface: '#FFFFFF',
    surfaceVariant: '#F0F2F5',
    glassBg: 'rgba(255, 255, 255, 0.85)',
    primary: '#3B5BDB',
    primaryContainer: '#D0D9FF',
    onPrimary: '#FFFFFF',
    secondary: '#6741D9',
    secondaryContainer: '#E2D9F3',
    error: '#E03131',
    errorContainer: '#FFE0E0',
    onError: '#FFFFFF',
    success: '#2B8A3E',
    successContainer: '#D3F9D8',
    warning: '#E67700',
    warningContainer: '#FFF3BF',
    textPrimary: '#1A1D23',
    textSecondary: '#6B7280',
    textDisabled: '#C9CDD5',
    textInverse: '#FFFFFF',
    border: '#E2E5EA',
    borderFocused: '#3B5BDB',
    overlay: 'rgba(0, 0, 0, 0.45)',
    skeleton: '#E9ECEF',
    accentGradientStart: '#3B5BDB',
    accentGradientEnd: '#6741D9',
  },
  spacing,
  radii,
  typography,
  shadows: {
    card: {
      shadowColor: '#1A1D23',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    cardHover: {
      shadowColor: '#1A1D23',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 16,
      elevation: 6,
    },
    modal: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 24,
      elevation: 12,
    },
  },
};
