import { Theme, spacing, radii, typography } from './tokens';

export const lightTheme: Theme = {
  dark: false,
  colors: {
    background: '#F8F9FA',
    surface: '#FFFFFF',
    surfaceVariant: '#F1F3F5',
    primary: '#4263EB',
    primaryContainer: '#DBE4FF',
    onPrimary: '#FFFFFF',
    secondary: '#7048E8',
    secondaryContainer: '#E5DBFF',
    error: '#E03131',
    errorContainer: '#FFE3E3',
    onError: '#FFFFFF',
    success: '#2B8A3E',
    successContainer: '#D3F9D8',
    warning: '#E67700',
    warningContainer: '#FFF3BF',
    textPrimary: '#212529',
    textSecondary: '#868E96',
    textDisabled: '#CED4DA',
    textInverse: '#FFFFFF',
    border: '#DEE2E6',
    borderFocused: '#4263EB',
    overlay: 'rgba(0, 0, 0, 0.5)',
    skeleton: '#E9ECEF',
  },
  spacing,
  radii,
  typography,
  shadows: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    modal: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
    },
  },
};
